# Generated by Django 2.2.2 on 2019-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('F_Name', models.CharField(max_length=30)),
                ('M_Name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=5)),
                ('Contact', models.IntegerField(max_length=12)),
                ('mc', models.CharField(max_length=50)),
                ('mp', models.CharField(max_length=8)),
                ('my', models.IntegerField(max_length=5)),
                ('ic', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=8)),
                ('iy', models.IntegerField(max_length=5)),
                ('gc', models.CharField(max_length=50)),
                ('gp', models.CharField(max_length=8)),
                ('gy', models.IntegerField(max_length=5)),
                ('oc', models.CharField(max_length=50)),
                ('op', models.CharField(max_length=8)),
                ('oy', models.IntegerField(max_length=5)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('C_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
