# Generated by Django 2.2.2 on 2019-06-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeration',
            name='C_Password',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='gc',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='gy',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='ic',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='iy',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='mc',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='mp',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='my',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='oc',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='op',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='oy',
        ),
    ]
