# Generated by Django 2.2.2 on 2019-06-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20190624_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='mc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registeration',
            name='mp',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='registeration',
            name='my',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
