# Generated by Django 2.2.2 on 2019-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20190624_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='mc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='mp',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='my',
            field=models.IntegerField(max_length=5),
        ),
    ]
