# Generated by Django 2.2.2 on 2019-06-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20190624_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='C_Password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registeration',
            name='Email',
            field=models.EmailField(default='abc@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='registeration',
            name='Password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registeration',
            name='gc',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='registeration',
            name='gp',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='registeration',
            name='gy',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='registeration',
            name='ic',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='registeration',
            name='ip',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='registeration',
            name='iy',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='registeration',
            name='oc',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='registeration',
            name='op',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='registeration',
            name='oy',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
