# Generated by Django 2.2.2 on 2019-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20190624_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='RightAnsTxt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='StudentAns',
            field=models.IntegerField(default=0),
        ),
    ]
