# Generated by Django 2.2.2 on 2019-07-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='duration',
        ),
    ]
